### ISSUE TITLE
Build fails, multiple target patterns error

### ISSUE THREAD

**Issue by luckasRanarison** [d3adb5/build-qmk-fw#5]
I got the following issue when trying to build my firmware with this github action.

Workflow run: https://github.com/luckasRanarison/licorne.qmk/actions/runs/13473888987/job/37650659304
Configuration: https://github.com/luckasRanarison/licorne.qmk/tree/master/keyboards/crkbd/keymaps/luckasranarison

<details>
<summary>Workflow:</summary>

Workflow:
```yaml
name: QMK build

on:
  push:
    branches:
      - master

jobs:
  build-qmk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: d3adb5/build-qmk-fw@v1
        with:
          keyboard: crkbd/rev4_1/standard
          keymap: luckasranarison
          local-keymap-path: keyboards/crkbd/keymaps/luckasranarison
          output-dir: build

      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: build
```

</details>

Logs:
```
Run d3adb5/build-qmk-fw@v1
/usr/bin/docker run --name a3026aa3517901a4725a3259df4eb1108f0_c2e927 --label 230a30 --workdir /github/workspace --rm -e "INPUT_KEYBOARD" -e "INPUT_KEYMAP" -e "INPUT_LOCAL-KEYMAP-PATH" -e "INPUT_OUTPUT-DIR" -e "INPUT_CONTROLLER" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/licorne.qmk/licorne.qmk":"/github/workspace" 230a30:26aa3517901a4725a3259df4eb1108f0  "crkbd/rev4_1/standard" "luckasranarison" "" "build" "keyboards/crkbd/keymaps/luckasranarison"
Copying local keymap into /opt/qmk_firmware/keyboards/crkbd/keymaps
'keyboards/crkbd/keymaps/luckasranarison' -> '/opt/qmk_firmware/keyboards/crkbd/keymaps/luckasranarison'
'keyboards/crkbd/keymaps/luckasranarison/.clang-format' -> '/opt/qmk_firmware/keyboards/crkbd/keymaps/luckasranarison/.clang-format'
'keyboards/crkbd/keymaps/luckasranarison/config.h' -> '/opt/qmk_firmware/keyboards/crkbd/keymaps/luckasranarison/config.h'
'keyboards/crkbd/keymaps/luckasranarison/keymap.c' -> '/opt/qmk_firmware/keyboards/crkbd/keymaps/luckasranarison/keymap.c'
'keyboards/crkbd/keymaps/luckasranarison/rules.mk' -> '/opt/qmk_firmware/keyboards/crkbd/keymaps/luckasranarison/rules.mk'
user.qmk_home: None -> /opt/qmk_firmware
Ψ Wrote configuration to /github/home/.config/qmk/qmk.ini
Ψ Compiling keymap with gmake -r -R -f builddefs/build_keyboard.mk -s KEYBOARD=crkbd/rev4_1/standard KEYMAP=luckasranarison KEYBOARD_FILESAFE=crkbd_rev4_1_standard TARGET=crkbd_rev4_1_standard_luckasranarison VERBOSE=false COLOR=true SILENT=false QMK_BIN="qmk"


⚠ "git describe --abbrev=6 --dirty --always --tags" returned error code 128
builddefs/build_keyboard.mk:232: *** multiple target patterns.  Stop.
0s
```
